import React,{useEffect,useMemo,useState} from 'react'
import {LayoutDashboard,CalendarDays,Users,ClipboardList,FileText,WalletCards,BarChart3,UserCog,Settings,Plus,MapPin,Clock,Wrench,AlertTriangle,CheckCircle2,Menu,LogOut,Cloud,CloudOff,RefreshCcw} from 'lucide-react'
import {supabase} from './supabase'
import Login from './Login'
import Clientes from './Clientes'
import {syncPendingChanges} from './sync'
const pages=[['dashboard','Dashboard',LayoutDashboard],['agenda','Agenda',CalendarDays],['clientes','Clientes',Users],['os','Ordens de Serviço',ClipboardList],['orcamentos','Orçamentos',FileText],['financeiro','Financeiro',WalletCards],['relatorios','Relatórios',BarChart3],['usuarios','Usuários',UserCog],['configuracoes','Configurações',Settings]]
const cards=[['OS abertas','8',ClipboardList],['Atendimentos hoje','4',CalendarDays],['Orçamentos pendentes','3',FileText],['A receber','R$ 4.850,00',WalletCards]]
const agendaDemo=[{hora:'08:00',cliente:'Condomínio Atlântico',tipo:'Preventiva',sistema:'CFTV',status:'Confirmado'},{hora:'10:30',cliente:'Edifício Central',tipo:'Corretiva',sistema:'Controle de Acesso',status:'Agendado'},{hora:'14:00',cliente:'Empresa Horizonte',tipo:'Visita Técnica',sistema:'Rede',status:'Agendado'}]
function Dashboard(){return <><div className="toolbar"><div><h2>Visão geral</h2><p>Acompanhe o movimento da FORTAL TECH.</p></div><button className="primary"><Plus size={18}/> Nova OS</button></div><div className="demoBanner">Os indicadores do Dashboard ainda são demonstrativos e serão conectados ao banco nas próximas etapas.</div><div className="cards">{cards.map(([l,v,I])=><div className="card" key={l}><div className="cardIcon"><I size={22}/></div><div><span>{l}</span><strong>{v}</strong></div></div>)}</div><div className="grid2"><section className="panel"><div className="panelTitle"><div><h3>Agenda de hoje</h3><p>Próximos atendimentos</p></div><CalendarDays size={20}/></div>{agendaDemo.map(a=><div className="agendaItem" key={a.hora+a.cliente}><div className="time"><Clock size={16}/>{a.hora}</div><div className="grow"><b>{a.cliente}</b><span>{a.tipo} • {a.sistema}</span></div><span className="badge">{a.status}</span></div>)}</section><section className="panel"><div className="panelTitle"><div><h3>Pendências técnicas</h3><p>Itens que exigem atenção</p></div><AlertTriangle size={20}/></div><div className="pending"><b>Condomínio Atlântico</b><span>Substituir câmera 08</span></div><div className="pending"><b>Edifício Central</b><span>Aguardando orçamento de fonte</span></div><div className="pending ok"><CheckCircle2 size={18}/><span>Demais atendimentos em dia</span></div></section></div></>}
function Agenda(){return <><div className="toolbar"><div><h2>Agenda</h2><p>Controle de visitas, retornos e atendimentos.</p></div><button className="primary"><Plus size={18}/> Novo agendamento</button></div><section className="panel"><div className="agendaHeader"><button>Hoje</button><button>Semana</button><button>Mês</button></div>{agendaDemo.map(a=><div className="agendaItem large" key={a.hora+a.cliente}><div className="time"><Clock size={16}/>{a.hora}</div><div className="grow"><b>{a.cliente}</b><span>{a.tipo} • {a.sistema}</span></div><button className="ghost"><MapPin size={16}/> Rota</button><span className="badge">{a.status}</span></div>)}</section></>}
const Placeholder=({title})=><section className="panel empty"><Wrench size={42}/><h2>{title}</h2><p>Módulo preparado para a próxima etapa.</p></section>
export default function App(){const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[page,setPage]=useState('dashboard'),[open,setOpen]=useState(false),[online,setOnline]=useState(navigator.onLine),[syncStatus,setSyncStatus]=useState('synced')
 useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[])
 useEffect(()=>{(async()=>{if(!session?.user||!supabase){setProfile(null);return}const {data}=await supabase.from('profiles').select('*').eq('id',session.user.id).single();setProfile(data)})()},[session])
 useEffect(()=>{const on=async()=>{setOnline(true);if(supabase)await syncPendingChanges(supabase,setSyncStatus)},off=()=>{setOnline(false);setSyncStatus('pending')};window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[])
 const current=useMemo(()=>pages.find(p=>p[0]===page),[page]);if(loading)return <div className="boot">Carregando FORTAL TECH...</div>;if(!supabase)return <div className="boot errorBox">Supabase não configurado. Verifique as variáveis de ambiente.</div>;if(!session)return <Login supabase={supabase}/>;const role=profile?.perfil==='admin'?'ADMINISTRADOR':'TÉCNICO';const visible=pages.filter(([id])=>profile?.perfil==='admin'||!['financeiro','relatorios','usuarios','configuracoes','orcamentos'].includes(id))
 return <div className="app"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="logo">FT</div><div><b>FORTAL TECH</b><span>Gestão Técnica</span></div></div><nav>{visible.map(([id,l,I])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setOpen(false)}}><I size={19}/>{l}</button>)}</nav><div className="profile"><div className="avatar">{(profile?.nome||session.user.email||'US').slice(0,2).toUpperCase()}</div><div className="profileText"><b>{profile?.nome||session.user.email}</b><span>{role}</span></div><button className="logoutBtn" onClick={()=>supabase.auth.signOut()}><LogOut size={17}/></button></div></aside><main><header><button className="menuBtn" onClick={()=>setOpen(!open)}><Menu/></button><div><span className="eyebrow">FORTAL TECH</span><h1>{current?.[1]}</h1></div><button className={`connection ${online?'online':'offline'}`} onClick={()=>syncPendingChanges(supabase,setSyncStatus)}>{online?<Cloud size={16}/>:<CloudOff size={16}/>} {!online?'Offline':syncStatus==='syncing'?'Sincronizando...':syncStatus==='pending'?'Pendente':'Online'} {syncStatus==='syncing'&&<RefreshCcw className="spin" size={14}/>}</button></header><div className="content">{page==='dashboard'?<Dashboard/>:page==='agenda'?<Agenda/>:page==='clientes'?<Clientes supabase={supabase} setSyncStatus={setSyncStatus}/>:<Placeholder title={current?.[1]}/>}</div></main></div>}
