import HistoricoCliente from './HistoricoCliente'
import React,{useEffect,useMemo,useState} from 'react'
import {Plus,Search,MapPin,Pencil,Trash2,X,Save,Phone,Building2,WifiOff,RefreshCcw} from 'lucide-react'
import {cacheClientes,getCachedClientes,saveLocalCliente,removeLocalCliente,queueChange} from './offline'
import {syncPendingChanges} from './sync'
const vazio={nome:'',documento:'',telefone:'',email:'',cep:'',endereco:'',numero:'',complemento:'',bairro:'',cidade:'',uf:'',responsavel:'',cargo_responsavel:'',latitude:'',longitude:'',observacoes:''}
export default function Clientes({supabase,setSyncStatus}){
 const [historico,setHistorico]=useState(null)
  const [clientes,setClientes]=useState([]),[busca,setBusca]=useState(''),[modal,setModal]=useState(false),[editando,setEditando]=useState(null),[form,setForm]=useState(vazio),[loading,setLoading]=useState(true),[erro,setErro]=useState('')
 async function carregar(){setLoading(true);setErro('');try{if(navigator.onLine){const {data,error}=await supabase.from('clientes').select('*').order('nome');if(error)throw error;await cacheClientes(data||[]);setClientes(data||[])}else setClientes(await getCachedClientes())}catch(e){setClientes(await getCachedClientes());setErro('Sem conexão com o servidor. Exibindo dados disponíveis no aparelho.')}setLoading(false)}
 useEffect(()=>{carregar()},[])
 useEffect(()=>{const online=async()=>{await syncPendingChanges(supabase,setSyncStatus);await carregar()};window.addEventListener('online',online);return()=>window.removeEventListener('online',online)},[supabase])
 const filtrados=useMemo(()=>{const q=busca.toLowerCase().trim();return !q?clientes:clientes.filter(c=>[c.nome,c.documento,c.telefone,c.responsavel,c.cidade].filter(Boolean).join(' ').toLowerCase().includes(q))},[clientes,busca])
 function novo(){setEditando(null);setForm(vazio);setModal(true)}
 function editar(c){setEditando(c);setForm({...vazio,...c});setModal(true)}
 async function salvar(e){e.preventDefault();setErro('');const payload={...form,id:editando?.id||crypto.randomUUID(),latitude:form.latitude===''?null:Number(form.latitude),longitude:form.longitude===''?null:Number(form.longitude),updated_at:new Date().toISOString()};try{if(navigator.onLine){const clean={...payload};delete clean._syncStatus;const {data,error}=await supabase.from('clientes').upsert(clean,{onConflict:'id'}).select().single();if(error)throw error;await saveLocalCliente(data,'synced')}else{await saveLocalCliente(payload,'pending');await queueChange('clientes','upsert',payload);setSyncStatus('pending')}setModal(false);await carregar()}catch(e){if(!navigator.onLine){await saveLocalCliente(payload,'pending');await queueChange('clientes','upsert',payload);setSyncStatus('pending');setModal(false);await carregar()}else setErro(e.message||'Não foi possível salvar o cliente.')}}
 async function excluir(c){if(!confirm(`Excluir o cliente "${c.nome}"?`))return;if(navigator.onLine){const {error}=await supabase.from('clientes').delete().eq('id',c.id);if(error){setErro(error.message);return}}else{await queueChange('clientes','delete',{id:c.id});setSyncStatus('pending')}await removeLocalCliente(c.id);await carregar()}
 function rota(c){const destino=c.latitude&&c.longitude?`${c.latitude},${c.longitude}`:[c.endereco,c.numero,c.bairro,c.cidade,c.uf,c.cep].filter(Boolean).join(', ');if(!destino)return alert('Este cliente ainda não possui endereço cadastrado.');window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(destino)}`,'_blank')}
 function capturar(){if(!navigator.geolocation)return alert('Geolocalização não disponível.');navigator.geolocation.getCurrentPosition(p=>setForm(f=>({...f,latitude:p.coords.latitude.toFixed(7),longitude:p.coords.longitude.toFixed(7)})),()=>alert('Não foi possível obter a localização. Verifique a permissão do GPS.'))}
 return <><div className="toolbar"><div><h2>Clientes</h2><p>Cadastro, localização e histórico da sua base de clientes.</p></div><button className="primary" onClick={novo}><Plus size={18}/> Novo cliente</button></div>{!navigator.onLine&&<div className="offlineNotice"><WifiOff size={17}/> Você está offline. Alterações serão sincronizadas automaticamente.</div>}{erro&&<div className="warningBox">{erro}</div>}<section className="panel"><div className="searchBar"><Search size={18}/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar cliente, documento, telefone ou responsável..."/><button className="ghost" onClick={async()=>{await syncPendingChanges(supabase,setSyncStatus);await carregar()}}><RefreshCcw size={16}/> Sincronizar</button></div>{loading?<div className="loadingText">Carregando clientes...</div>:filtrados.length===0?<div className="emptySmall"><Building2 size={34}/><b>Nenhum cliente encontrado</b><span>Cadastre o primeiro cliente da FORTAL TECH.</span></div>:<div className="clientList">{filtrados.map(c=><div className="clientRow" key={c.id}><div className="clientMain"><div className="clientAvatar">{(c.nome||'C').slice(0,2).toUpperCase()}</div><div><b>{c.nome}</b><span>{[c.responsavel,c.telefone].filter(Boolean).join(' • ')||'Sem contato informado'}</span><small>{[c.endereco,c.numero,c.bairro,c.cidade,c.uf].filter(Boolean).join(', ')}</small>{c._syncStatus==='pending'&&<em>Aguardando sincronização</em>}</div></div><div className="rowActions">{c.telefone&&<a className="iconBtn" href={`tel:${c.telefone}`}><Phone size={17}/></a>}<button className="iconBtn" onClick={()=>rota(c)}><MapPin size={17}/></button><button className="historyBtn" onClick={()=>setHistorico(c)} title="Ver histórico">Histórico</button>
              <button className="iconBtn" onClick={()=>editar(c)}><Pencil size={17}/></button><button className="iconBtn danger" onClick={()=>excluir(c)}><Trash2 size={17}/></button></div></div>)}</div>}</section>{modal&&<div className="modalBackdrop"><div className="modal"><div className="modalHead"><div><span className="eyebrow">FORTAL TECH</span><h2>{editando?'Editar cliente':'Novo cliente'}</h2></div><button className="iconBtn" onClick={()=>setModal(false)}><X/></button></div><form onSubmit={salvar}><div className="formGrid">
 {[["nome","Cliente / Condomínio *",true],["documento","CPF / CNPJ"],["telefone","Telefone"],["email","E-mail"],["cep","CEP"],["endereco","Endereço"],["numero","Número"],["complemento","Complemento"],["bairro","Bairro"],["cidade","Cidade"],["uf","UF"],["responsavel","Responsável"],["cargo_responsavel","Cargo / Função"],["latitude","Latitude"],["longitude","Longitude"]].map(([k,l,req])=><div key={k} className={`field ${k==='nome'||k==='endereco'?'span2':''}`}><label>{l}</label><input required={!!req} value={form[k]??''} onChange={e=>setForm({...form,[k]:k==='uf'?e.target.value.toUpperCase():e.target.value})}/></div>)}
 <div className="field span2"><button type="button" className="ghost full" onClick={capturar}><MapPin size={17}/> Capturar localização atual</button></div><div className="field span2"><label>Observações</label><textarea rows="4" value={form.observacoes||''} onChange={e=>setForm({...form,observacoes:e.target.value})}/></div></div><div className="modalActions"><button type="button" className="ghost" onClick={()=>setModal(false)}>Cancelar</button><button className="primary"><Save size={17}/> Salvar cliente</button></div></form></div></div>}      {historico&&<HistoricoCliente supabase={supabase} cliente={historico} onClose={()=>setHistorico(null)}/>}
  </>
}
